### ISSUE TITLE
Cursor doesn't line up with active line.

### ISSUE THREAD

**Issue by ssateneth** [spiralofhope/_DevPad.GUI#1]
The active line doesn't match up with the cursor when editing a page.

The cursor will go down more than the actual line the further down you are on the page (noticeable by line 19, obvious around line 100+) so it becomes very difficult to edit pages that have more lines.

# Reproduction with Leatrix Plus

http://www.curse.com/addons/wow/leatrix-plus

- Restart with other addons disabled
- Fill the chat area with text of varying widths
  -  The number of lines of the text matters for this test
- Control-click the current chat's tab
  -  The view/copy window appears
- Click the view/copy window
- Control-a
- Observe the highlight lining up with the text
- Escape > System
  -  } Graphics
      -  Display mode:  (see below)
      -  Resolution:    (see below)
  -  } Advanced
        -  [x] UI Scale  (checked ON)
        -  UI Scale  1.0

The problem is that with some resolutions, the background highlight does not match behind with the text.  The offset exaggerates with taller text (but not with more characters).  When the UI scale is disabled, from what I can see things line up in all circumstances.  Specific font sizes also correct this problem.

In other addons which have a text area which is editable, not only is the highlighting wrong, when the user types the characters appear in the lines above where the cursor is drawn.

## others face this

- https://github.com/spiralofhope/_DevPad.GUI/issues/1#issuecomment-326695445
- http://www.wowinterface.com/forums/showthread.php?p=324922
- https://eu.battle.net/forums/en/wow/topic/17616703164#1

## To do

To allow editing in the above text popup, comment-out:

``` lua
editBox:EnableKeyboard(false)
editBox:SetScript("OnKeyDown", function() end)
```

# old notes

## Facts

(spiralofhope's additions)

- Somewhere in `_DevPad.GUI.Editor.lua` is almost certainly where the solution is.
- It being a text or script item does not matter
- The amount of text in the test file/script does not matter.
  -  For example, having a lot of content on line 1 does not influence the behavior when typing further down.
- The highlight-bar is also not correct, but its position-incorrectness is different than the typing-incorrectness
- The more the cursor is down, the more pronounced the problem
- There appears to be a "sweet spot" when playing with font size and screen resolution, where the bar and text-insertion are correct.
  -  A font size of `14` for `1920x1080`
  -  A font size of `10` for `1229x768`
- When finding a spot where the highlight bar is wrong, and changing the font, both the font and highlight bar are correct at the same time.
- The position of the line is calculated in pixels
  -  I find this extremely odd
  -  This is the root of this entire problem.
- When a font sweet spot is found, having a huge height of text does not matter.
- There is no reference to screen size or scale in `_DevPad.GUI.Editor.lua`

## Things I've tried

(aside from exploring all of the above)

- Performed all tests with all optional features disabled:

```
_DevPad.GUI.List.Search_optional.lua
_DevPad.GUI.Editor.Color_optional.lua
_DevPad.GUI.Editor.History_optional.lua
_DevPad.GUI.Editor.LineNumbers_optional.lua
```
- Reviewed all API changes all the way back to patch 5.0.4
  -  Nothing applies
  -  https://wow.gamepedia.com/Category:World_of_Warcraft_API/Changes
- Audited all of `_DevPad.GUI.Editor.lua`
  -  Although there are great comments, a lot of it is a mystery.
      -  Everything seems organized, but I am bothered by the notion that things are still named strangely.
- Added debugging messages all over `_DevPad.GUI.Editor.lua` to review what's going on
- Hard-coded various references to line height and cursor height.

## What I suspect / things to do

- A `y` setting is being decremented, and there is a rounding issue that is exaggerating a problem.
  -  I hate floats.
      -  Can I change from this to int?  I've looked around, and nothing seems appropriate or works!  I'm missing something fundamental about lua.
  -  I have debugged/audited all `y` math to no avail.  More work must be done.

**Comment by spiralofhope** [comment]
I've never really looked into the code for this addon, but I'll definitely spend some time trying to fix this bug.

**Comment by ssateneth** [comment]
In case you wanted a visual example, heres the issue around line 80. It's less pronounced the lower the line number, and much worse the higher it is. http://i.imgur.com/UAlH9vo.gifv

**Comment by spiralofhope** [comment]
Reproduced.

I'll work on this today.  Wish me luck!

**Comment by ssateneth** [comment]
Thank you! Also do you take donations? Can't think of not using _Devpad. Wowlua doesnt have a folder system so its meh.

**Comment by spiralofhope** [comment]
We're in the same boat, I don't think I can live without _DevPad.. I've done some really magical things with it.  I've also tried other addons, and they're lacking.

Keep in mind I'm not the creator of this addon, I'm just trying to muddle through some updates.  I'm not even supposed to be a programmer!  So it doesn't feel right to take donations.  You might be able to contact saiket, his email address is listed here:
https://github.com/Saiket

Who knows, maybe I'll do some magic with it.. I surprised myself with my TidyBar fork:
http://blog.spiralofhope.com/?p=19242
https://github.com/spiralofhope/TidyBar

If you insist on donations, you could help my hosting:
https://blog.spiralofhope.com/?p=22776
.. but I haven't worked hard enough to justify their $10 minimum.

FYI you inspired me to also fork the proper _DevPad:
https://github.com/spiralofhope/_DevPad

--

_Now on to the interesting bit:_  If you increase the font size by two, the issue goes away, at least for a 100 line script.

**Comment by ssateneth** [comment]
I did the font thing before making the ticket. It alleviates it somewhat, but does not make it go away. A smaller font will have a relatively larger 'error', while a larger font will need many more lines to make the issue become apparent, but I don't want to work with a 40 point font just so I know what line I'm editing.

**Comment by spiralofhope** [comment]
Bloody hell is this difficult to track down.

I'll work on this some more in the near future.  Maybe during a break something will come to me.

**Comment by spiralofhope** [comment]
Fixed in the upcoming 7.3.0.2

I finally tracked this down.  It was a scaling problem.

A child frame in one file is inheriting a size that's hard-coded for a parent whose code is in a second file!  Apparently writing the essay of ideas and taking a break helped a lot.

The solution was to force the scaling of the editor window from the inherited 0.9 back up to 1.  I tried doing this more gracefully, but it didn't work out.  Maybe later.  Because this enlarges the text, I made it so you can now change the font size in steps of 1 (down from 2).

Please double-check your font size.  You will likely have to reduce your font by one step to make it comfortable again.  I am also sensitive to the text size, but this seems good to me.  I hope it is also good for you. 

Thanks for your inspiration, the release will be up shortly.  This was an interesting afternoon.

**Comment by ssateneth** [comment]
I grabbed the new versions of _Devapd and its GUI from your github and some things still arent quite right. For one, now the line numbers are missing. The other is the cursor still isn't matching :(. Picture included. I just highlighted everything so you can see a little better. The cursor/highlighting is still too big vertically compared to the text itself.

http://i.imgur.com/UhnqhBB.png

Edit: I also wanted to add that your addon isnt the only one exhibiting this. SimPermut also shows this error.

http://i.imgur.com/FfO3lXM.png
http://i.imgur.com/Z3bAATc.gifv

**Comment by spiralofhope** [comment]
Crap, I forgot to un-comment some lines for the line numbering, search, etc.  Fixed in 7.3.0.3.

It worked for me, but I'll do some more rigorous testing to try to reproduce this bug.

If my solution works, then I could probably fix SimPermut too.  Embarrassingly, it turned out to be pretty simple.

**Comment by spiralofhope** [comment]
_I am not able to reproduce your highlight or typing issue._

Things I have tried:

- A lua text
- Lots of (valid) code
- 1920x1080 fullscreen-windowed
- Windowed, resized to various dimensions
- A lower and greater size of font

I'm highlighting and typing, and everything is working as-expected.  Are you doing anything different from what I tried?

It's very odd this isn't fixed for you.  Did you quit and re-start the game?  Are all other addons disabled for your testing?

**Comment by ssateneth** [comment]
Restarted the PC. For what its worth, I play windowed, my ingame resolution is 5136 x 1386 (I use a viewport addon to render game world on my center monitor while rendering other elements like map, quests, chat boxes, etc, on my right monitor), my UI scale slider is checked and is set to the smallest value. I'll disable every addon except devpad and see what happens.

edit: All addons disabled except _Devpad and GUI, no worky.
Changed screen resolution, nada
Disabled UI scale, and I got a perfect alignment with only 1 font size. Refer the line number to the last cursor spot. Heres a video!

http://i.imgur.com/ed95CPq.gifv

**Comment by spiralofhope** [comment]
A high resolution exaggerated the problem for me in my earlier testing.  Please try reproducing with much smaller resolutions to see if anything changes.

I think I have the software to fake a very high resolution for testing, if it comes to that.

**Comment by ssateneth** [comment]
As a baseline, windowed, no addons, no UI scale, 1024 x 768, they all align perfectly, as do all resolutions with a vertical size of 768.
1280x960 the alignment fails on all but 1 size.
2048 x 1152 (1.5x Y size and 16:9) the alignment fails on all sizes.
1536 x 1152 (1.5x Y size and 4:3) same result as above.
1440 x 900 (built-in resolution) same result as above.
I was unable to test 2048 x 1536 (2x Y 4:3) but it seemed correct on only the 1 font size (dont know the exact resolution it set, probably some Y about 40 some pixels smaller than 1440)

EDIT: The window sizing application I was using probably does not size with respect to the indie of the window and not the outside, still testing.

Another edit: Got it to size correctly from the inside. When Y = 768 * 1.5 (1152), every other font size is aligned correctly.

**Comment by spiralofhope** [comment]
I'm able to reproduce it again.

Curiously I'm only able to reproduce it on

- 720 x 576
  -  What an odd resolution.
- 1280 x 1024

I have raid tonight, but I'll keep working on this.

**Comment by spiralofhope** [comment]
Oh my god this bug also exists in SuperDuperMacro.  I wonder if this exists with all editors, and it's a bug at Blizzard's end.

**Comment by ssateneth** [comment]
I brought it up in the SimulationCraft and SimPermut channels.

[5:02 PM] Ssateneth: is anyone here thats active responsible for the SimPermut addon?
[5:03 PM] Ssateneth: Theres a glitch with textboxes and cursor/highligh not matching the position of the text (its not just your addon though, other addons that use textboxes and cursors also have that problem too)
[5:04 PM] Zulandia: Pretty sure that's a WoW issue not simpermut in particular...but @Kutikuti is who you're looking for
[5:04 PM] seriallos: Yeah, it's affecting a bunch of addons
[5:04 PM] Ssateneth: https://github.com/spiralofhope/_DevPad.GUI/issues/1
GitHub
Cursor doesn't line up with active line. · Issue #1 · spiralofhope/_DevPad.GUI
The active line doesn't match up with the cursor when editing a page. The cursor will go down more than the actual line the further down you are on the page (noticeable by line 19, obvious around l...

[5:04 PM] Ssateneth: 7.3 broke itttttttt
[5:05 PM] Kutikuti: yeah that's an issue on blizzard's end
[5:05 PM] Kutikuti: reported it but that's the only thing i can do

**Comment by Kutikuti** [comment]
Hi, I sent a ticket to blizzard french support. They told me that they don't manage that but that this will be brought up to the dev team. Also, they asked me to do a topic on the official forum. I made one on the EU forum if you want to follow : https://eu.battle.net/forums/en/wow/topic/17616703164#1
If you can you could do a similar one on the US forum as it's clear that this issue is on Blizzard's end.

**Comment by spiralofhope** [comment]
I'm able to reproduce this problem with other addons, and I've reached out to a developer for an assist.

**Comment by spiralofhope** [comment]
I just saw your additions.  Thanks gang, it's nice to see I'm not insane.

**Comment by spiralofhope** [comment]
Since other authors are hit by this, I'm taking a break from this to let the Smart People think about it.

I've edited the main description with a simple way of reproducing this.  Maybe I could carve out some code for a simpler test case, but I'm too burnt out to learn how.

[edit] I was given a simple way to test.  The description was edited to add that.

**Comment by spiralofhope** [comment]
A fix is incoming, I'm just experimenting a little more.

**Comment by ssateneth** [comment]
Sounds promising!

**Comment by spiralofhope** [comment]
Fixed in 7.3.0.4

Tested with the additional cases - font sizes, fullscreen or windowed, various resolution changes, stretching/resizing a windowed screen, and turning the game's UI scaling checkbox on or off.

@ssateneth - While I'm confident I fixed it on my end, please give it a good once-over for your higher resolutions, because I can't test those.

**Comment by ssateneth** [comment]
Cursor bug seems squashed once and for all! The only side effect is the size of the _Devpad GUI is pretty large now. I don't see a setting to change the size of the GUI itself. Would be nice to make it smaller or adjustable or the same size as pre-fix.

--not correct vv
This might have something to do with my very long aspect ratio as when I changed from 1 screen to 2 screens. Damage numbers increased vastly in size when I did that but nothing else really seemed to change (aside from needing to position some things relative to WorldFrame instead of UIParent)
--not correct ^^

Edit: Using MoveAnything to adjust the scale of the frame size, it seems that the GUI used to inherit whatever UI scale size the game set. Now it is hardcoded (?) to a scale size of 1. Changing the scale size to 0.65 almost perfectly matches pre-patch behavior. Disabling UI Scaling causes UI elements to appear slightly smaller than 0.65 UI scale. Whatever the case is, _Devpad GUI should probably inherit the game's UI scale, unless this specific part was changed to fix the cursor issue and was the root cause anyways.

another edit: Yeah it seems setting the scale of the frame to 1 was the fix as changing the scale to something smaller breaks the cursor again. So it's a workaround for now to have scale set to 1.

**Comment by spiralofhope** [comment]
I'm aware of the size issue of that left panel.  I took a glance at it but nothing came to mind.  I had already made a reminder-ticket for that:

#14 - Change the font of the main list 

The entire root of this problem _began_ with it inheriting the scaling from Blizzard.  The only solution was to (basically) hard-code the scale to 1.  Every addon will have to be detached from Blizzard and handle their own scaling separately now.

I don't know how to do that handling, so it's stuck at 1 until I learn that, probably during another pass at #14.  I also have another addon to examine, to learn from their example.

**Comment by spiralofhope** [comment]
This issue had a font (scale) side-effect in the list.  A hard-coded solution has been introduced in 7.3.0.6

Further updates to that separate issue will be in #14 - Change the font of the main list.  That issue is not simple, as a font preference is spread between a couple of files in `_DevPad.GUI`, and also between the two `_DevPad` and `_DevPad.GUI` addons!

**Do not forget to also update [_DevPad](https://github.com/spiralofhope/_DevPad)**

**Comment by ssateneth** [comment]
I want to re-open this ticket. I reverted GUI back to 7.3.0.3 (before these fixes were put in) and the misaligned text cursor is no longer a thing. It seems blizzard fixed their issue, so I would like to submit a request to revert this change to take advantage of a smaller UI.

**Comment by spiralofhope** [comment]
I'm keeping this ticket closed and opening a fresh ticket to keep things clean.

**Comment by spiralofhope** [comment]
Fixed in 8.0.1.2

**Comment by spiralofhope** [comment]
This has reappeared with 8.2, perhaps for a different reason.

**Comment by spiralofhope** [comment]
I haven't seen this problem in a long time; closing.
